name: Create Repo - Assign
on:
  issues:
    types:
      - opened
env:
  LGTM_TEAM: lgtm-reviewers
jobs:
  assign:
    name: Assign new issue
    runs-on: ubuntu-20.04
    if: contains(github.event.issue.labels.*.name, 'create_repo_multi_org') && github.event.action == 'opened'
    steps:
      - name: Acknowledge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MULTI_ORG_TOKEN }}
          script: |
            const body = `
            @${context.actor} : Hey!  Let's get this issue assigned to someone from the @${context.repo.owner}/${process.env.LGTM_TEAM} team while we validate the request.
            `

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            })

      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v1.4.0
        with:
          repo-token: ${{ secrets.MULTI_ORG_TOKEN }}
          teams: ${{ env.LGTM_TEAM }}
          numOfAssignee: 1
